# Generated by Django 4.2.4 on 2023-09-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingvalues',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ratingvalues',
            name='value',
            field=models.CharField(default='', max_length=100),
        ),
    ]
