# Generated by Django 4.2.4 on 2023-09-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_ratingvalues_title_alter_ratingvalues_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingvalues',
            name='title',
        ),
        migrations.AddField(
            model_name='ratingvalues',
            name='uniqueid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ratingvalues',
            name='value',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
